FROM mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye

# Install additional system packages
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    postgresql-client \
    redis-tools \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install global npm packages
RUN npm install -g typescript ts-node nodemon

# Configure git
RUN git config --global core.autocrlf input \
    && git config --global init.defaultBranch main
